version: '3'
networks:
  pulsar:
    driver: bridge
services:

  # MySQL8
  db_terceros:
    image: mysql:8
    hostname: mysqldb_terceros
    container_name: mysqldb_terceros
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=terceros
      - MYSQL_ROOT_PASSWORD=adminadmin
    profiles: ["db_terceros"]
    networks:
      - pulsar
    ports:
      - '3307:3306'
    expose:
      - 3307
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init_terceros.sql:/docker-entrypoint-initdb.d/init.sql

    # MySQL8
  db_ordenes:
    image: mysql:8
    hostname: mysqldb
    container_name: mysqldb_ordenes
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ordenes
      - MYSQL_ROOT_PASSWORD=adminadmin
    profiles: ["db_ordenes"]
    networks:
      - pulsar
    ports:
      - '3306:3306'
    volumes:
      - ./data_ordenes/mysql:/var/lib/mysql
      - ./init-orden.sql:/docker-entrypoint-initdb.d/init.sql 

# MySQL8
  db_pedidos:
     image: mysql:8
     hostname: mysqldb
     container_name: mysqldb_pedidos
     cap_add:
        - SYS_NICE
     restart: always
     environment:
            - MYSQL_DATABASE=pedidos
            - MYSQL_ROOT_PASSWORD=adminadmin
     profiles: [ "db_pedidos" ]
     networks:
        - pulsar
     ports:
        - '3308:3306'
     volumes:
        - ./data_pedidos/mysql:/var/lib/mysql
        - ./init-pedidos.sql:/docker-entrypoint-initdb.d/init.sql

# MySQL8
  saga_log:
     image: mysql:8
     hostname: mysqldb_saga
     container_name: mysqldb_saga
     cap_add:
        - SYS_NICE
     restart: always
     environment:
            - MYSQL_DATABASE=saga
            - MYSQL_ROOT_PASSWORD=adminadmin
     profiles: [ "db_saga" ]
     networks:
        - pulsar
     ports:
        - '3309:3306'
     volumes:
        - ./data_sagas/mysql:/var/lib/mysql
        - ./init_saga.sql:/docker-entrypoint-initdb.d/init.sql

#bodegas
  terceros:
    container_name: bodegas
    hostname: bodegas
    image: bodegas 
    profiles: ["bodegas"]
    networks:
      - pulsar

#bodegas
  saga:
    container_name: saga
    hostname: saga
    image: saga
    profiles: ["saga"]
    networks:
      - pulsar